#!/bin/sh
# num = test number
# cmd = command executed
# retstr = returned string from function
# retval = returned value
# expstr = expected string from function
# expval = expected value

evaluate() {
    if [ "$retstr" = "$expstr" ] && [ $retval -eq $expval ]; then
        printf "%bTest %s passed.%b\n" "\033[1;32m" "$num" "\033[0m"
    elif [ "$retstr" != "$expstr" ] && [ $retval -ne $expval ]; then
        echo
        printf '%b%s:%b\n' "\033[1;37m" "$num" "\033[0m"
        printf "cmd: (%s)\n" "$cmd"
        printf "retstr: (%b%s%b)\n" "\033[1;31m" "$retstr" "\033[0m"
        printf "expstr: (%b%s%b)\n" "\033[1;32m" "$expstr" "\033[0m"
        printf "retval: (%b%d%b)\n" "\033[1;31m" "$retval" "\033[0m"
        printf "expval: (%b%d%b)\n" "\033[1;32m" "$expval" "\033[0m"
        echo
    elif [ $retval -ne $expval ]; then
        echo
        printf '%b%s:%b\n' "\033[1;37m" "$num" "\033[0m"
        printf "cmd: (%s)\n" "$cmd"
        printf "retstr: (%s)\n" "$retstr"
        printf "expstr: (%s)\n" "$expstr"
        printf "retval: (%b%d%b)\n" "\033[1;31m" "$retval" "\033[0m"
        printf "expval: (%b%d%b)\n" "\033[1;32m" "$expval" "\033[0m"
        echo
    else
        echo
        printf '%b%s:%b\n' "\033[1;37m" "$num" "\033[0m"
        printf "cmd: (%s)\n" "$cmd"
        printf "retstr: (%b%s%b)\n" "\033[1;31m" "$retstr" "\033[0m"
        printf "expstr: (%b%s%b)\n" "\033[1;32m" "$expstr" "\033[0m"
        printf "retval: (%d)\n" "$retval"
        printf "expval: (%d)\n" "$expval"
        echo
    fi
}

num=001
IFS= read -r cmd <<'EOF'
safe_str 'LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789 |&;<>()$`\"'\''*?[]#~=%'
EOF
IFS= read -r expstr <<'EOF'
LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789 \|\&\;\<\>\(\)\$\`\\\"\'\*\?\[\]\#\~\=\%
EOF
retstr=$(safe_str 'LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789 |&;<>()$`\"'\''*?[]#~=%')
retval=$?
expval=0
evaluate;

num=002
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   '
EOF
IFS= read -r expstr <<'EOF'
  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  \|\&\;\<\>\(\)\$\`\\\"\'\*\?\[\]\#\~\=\%   
EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ')
retval=$?
expval=0
evaluate;

num=003
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' '0LT$\'
EOF
IFS= read -r expstr <<'EOF'
  \LE\LE KVA GAZA ̴͋Ṙ̷KA SI \TI 0123456789  |&;<>()\$`\\"'*?[]#~=%   
EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' '0LT$\')
retval=$?
expval=0
evaluate;

num=004
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' '0\LLLLLLLLLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\'
EOF
IFS= read -r expstr <<'EOF'
  \LE\LE KVA GAZA ̴͋Ṙ̷KA SI \TI 0123456789  |&;<>()\$`\\"'*?[]#~=\%   
EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' '0\LLLLLLLLLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\')
retval=$?
expval=0
evaluate;

num=005
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' 1
EOF
IFS= read -r expstr <<'EOF'
  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789     
EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  |&;<>()$`\"'\''*?[]#~=%   ' 1)
retval=$?
expval=0
evaluate;

num=006
IFS= read -r cmd <<'EOF'
safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???' 1
EOF
IFS= read -r expstr <<'EOF'
  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789       
EOF
retstr=$(safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???' 1)
retval=$?
expval=0
evaluate;

num=007
IFS= read -r cmd <<'EOF'
safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???' '00\LLLLLLLLLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\' 1
EOF
IFS= read -r expstr <<'EOF'
  EE KVA GAZA ̴͋Ṙ̷KA SI I 123456789  |&;<>()`"'*?[]#~=    ` ???
EOF
retstr=$(safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???' '00\LLLLLLLLLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\' 1)
retval=$?
expval=0
evaluate;

# caveat
num=008
IFS= read -r cmd <<'EOF'
safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???RRR' '00\LLLLLLL ̴͋Ṙ̷LLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\ ̴͋Ṙ̷' 1
EOF
IFS= read -r expstr <<'EOF'
  EE KVA GAZAKA SI I 123456789  |&;<>()`"'*?[]#~=    ` ???RRR
EOF
retstr=$(safe_str '  \LELE \KVA \GAZA\ ̴͋Ṙ̷\KA \SI \TI\ \0123456789\  |&;<>()\$\$$$$`\"'\''*?[]#~=% \ \$\ $ ` ???RRR' '00\LLLLLLL ̴͋Ṙ̷LLLLLLLLLLLL\LLLLT$$$$$$$$$$$$$$$$$$%%%\$\ ̴͋Ṙ̷' 1)
retval=$?
expval=0

num=009
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   '
EOF
IFS= read -r expstr <<'EOF'

EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ')
retval=$?
expval=1
evaluate;

num=010
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' '0\$$$^_^@_@!_!#_#\_\'
EOF
IFS= read -r expstr <<'EOF'

EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' '0\$$$^_^@_@!_!#_#\_\')
retval=$?
expval=1
evaluate;

num=011
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' 1
EOF
IFS= read -r expstr <<'EOF'

EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' 1)
retval=$?
expval=1
evaluate;

num=012
IFS= read -r cmd <<'EOF'
safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' '0\$$$^_^@_@!_!#_#\_\' 1
EOF
IFS= read -r expstr <<'EOF'

EOF
retstr=$(safe_str '  LELE KVA GAZA ̴͋Ṙ̷KA SI TI 0123456789  AaBbCcDd   ' '0\$$$^_^@_@!_!#_#\_\' 1)
retval=$?
expval=1
evaluate;
