#!/bin/sh

{ i=$(remstring 'lmao' "lmao GG lmao GG lmaoGGlmao GG lmao" 0 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG lmao GG lmaoGGlmao GG lmao'" ;} && echo

{ i=$(remstring 'lmao' "GG lmao GG lmaoGGlmao GG lmao" 0 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG lmaoGGlmao GG lmao'" ;} && echo

{ i=$(remstring 'lmao' "GG lmaoGGlmao GG lmao" 0 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GGlmao GG lmao'" ;} && echo

{ i=$(remstring 'lmao' "GGlmao GG lmao" 0 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG lmao'" ;} && echo

{ i=$(remstring 'lmao' "GG lmao" 0 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG'" ;}

echo && echo

{ i=$(remstring 'lmao' "lmao GG lmaoGGlmao GG lmao GG lmao" 1 3) && \
echo "GOT: '$i'" && echo "EXP: 'lmao GG lmaoGGlmao GG lmao GG'" ;} && echo

{ i=$(remstring 'lmao' "lmao GG lmaoGGlmao GG lmao GG" 1 3) && \
echo "GOT: '$i'" && echo "EXP: 'lmao GG lmaoGGlmao GG GG'" ;} && echo

{ i=$(remstring 'lmao' "lmao GG lmaoGGlmao GG" 1 3) && \
echo "GOT: '$i'" && echo "EXP: 'lmao GG lmaoGG GG'" ;} && echo

{ i=$(remstring 'lmao' "lmao GG GGlmao" 1 3) && \
echo "GOT: '$i'" && echo "EXP: 'lmao GG GG'" ;} && echo

{ i=$(remstring 'lmao' "lmao GG" 1 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG'" ;}

echo && echo

{ i=$(remstring 'lmao' "lmao GG lmao GG lmaoGGlmao GG lmao" 2 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG GG GG'" ;} && echo

{ i=$(remstring 'lmao' "GG lmao GG lmaoGGlmao GG lmao" 2 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG GG GG'" ;} && echo

{ i=$(remstring 'lmao' "GG lmaoGGlmao GG lmao" 2 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG GG'" ;} && echo

{ i=$(remstring 'lmao' "GGlmao GG lmao" 2 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG GG'" ;} && echo

{ i=$(remstring 'lmao' "GG lmao" 2 3) && \
echo "GOT: '$i'" && echo "EXP: 'GG'" ;}
